<!DOCTYPE html>












  


<html class="theme-next muse use-motion" lang="">
<head>
  <meta charset="UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2"/>
<meta name="theme-color" content="#222">












<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />






















<link href="/lib/font-awesome/css/font-awesome.min.css?v=4.6.2" rel="stylesheet" type="text/css" />

<link href="/css/main.css?v=6.4.2" rel="stylesheet" type="text/css" />


  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png?v=6.4.2">


  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png?v=6.4.2">


  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png?v=6.4.2">


  <link rel="mask-icon" href="/images/logo.svg?v=6.4.2" color="#222">









<script type="text/javascript" id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/',
    scheme: 'Muse',
    version: '6.4.2',
    sidebar: {"position":"left","display":"post","offset":12,"b2t":false,"scrollpercent":false,"onmobile":false},
    fancybox: false,
    fastclick: false,
    lazyload: false,
    tabs: true,
    motion: {"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}},
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>


  




  <meta name="description" content="刚接触Python的时候，简单的异常处理已经可以帮助我们解决大多数问题，但是随着逐渐地深入，我们会发现有很多情况下简单的异常处理已经无法解决问题了，如下代码，单纯的打印异常所能提供的信息会非常有限。 &amp;lt;!--more--&amp;gt; 12345678910111213def func1():    raise Exception(&amp;quot;--func1 exception--&amp;quot;)d">
<meta name="keywords" content="computer, programming, data science, deep learning">
<meta property="og:type" content="article">
<meta property="og:title" content="Python Traceback 详解">
<meta property="og:url" content="http://yoursite.com/2017/02/07/python_traceback/index.html">
<meta property="og:site_name" content="Geekpy&#39;s Blog">
<meta property="og:description" content="刚接触Python的时候，简单的异常处理已经可以帮助我们解决大多数问题，但是随着逐渐地深入，我们会发现有很多情况下简单的异常处理已经无法解决问题了，如下代码，单纯的打印异常所能提供的信息会非常有限。 &amp;lt;!--more--&amp;gt; 12345678910111213def func1():    raise Exception(&amp;quot;--func1 exception--&amp;quot;)d">
<meta property="og:locale" content="default">
<meta property="og:updated_time" content="2018-08-12T10:14:46.316Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Python Traceback 详解">
<meta name="twitter:description" content="刚接触Python的时候，简单的异常处理已经可以帮助我们解决大多数问题，但是随着逐渐地深入，我们会发现有很多情况下简单的异常处理已经无法解决问题了，如下代码，单纯的打印异常所能提供的信息会非常有限。 &amp;lt;!--more--&amp;gt; 12345678910111213def func1():    raise Exception(&amp;quot;--func1 exception--&amp;quot;)d">



  <link rel="alternate" href="/atom.xml" title="Geekpy's Blog" type="application/atom+xml" />




  <link rel="canonical" href="http://yoursite.com/2017/02/07/python_traceback/"/>



<script type="text/javascript" id="page.configurations">
  CONFIG.page = {
    sidebar: "",
  };
</script>

  <title>Python Traceback 详解 | Geekpy's Blog</title>
  









  <noscript>
  <style type="text/css">
    .use-motion .motion-element,
    .use-motion .brand,
    .use-motion .menu-item,
    .sidebar-inner,
    .use-motion .post-block,
    .use-motion .pagination,
    .use-motion .comments,
    .use-motion .post-header,
    .use-motion .post-body,
    .use-motion .collection-title { opacity: initial; }

    .use-motion .logo,
    .use-motion .site-title,
    .use-motion .site-subtitle {
      opacity: initial;
      top: initial;
    }

    .use-motion {
      .logo-line-before i { left: initial; }
      .logo-line-after i { right: initial; }
    }
  </style>
</noscript>

</head>

<body itemscope itemtype="http://schema.org/WebPage" lang="default">

  
  
    
  

  <div class="container sidebar-position-left page-post-detail">
    <div class="headband"></div>

    <header id="header" class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-wrapper">
  <div class="site-meta ">
    

    <div class="custom-logo-site-title">
      <a href="/" class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">Geekpy's Blog</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
    
  </div>

  <div class="site-nav-toggle">
    <button aria-label="Toggle navigation bar">
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>



<nav class="site-nav">
  
    <ul id="menu" class="menu">
      
        
        
        
          
          <li class="menu-item menu-item-home">
    <a href="/" rel="section">
      <i class="menu-item-icon fa fa-fw fa-home"></i> <br />Home</a>
  </li>
        
        
        
          
          <li class="menu-item menu-item-about">
    <a href="/about/" rel="section">
      <i class="menu-item-icon fa fa-fw fa-user"></i> <br />About</a>
  </li>
        
        
        
          
          <li class="menu-item menu-item-tags">
    <a href="/tags/" rel="section">
      <i class="menu-item-icon fa fa-fw fa-tags"></i> <br />Tags</a>
  </li>
        
        
        
          
          <li class="menu-item menu-item-categories">
    <a href="/categories/" rel="section">
      <i class="menu-item-icon fa fa-fw fa-th"></i> <br />Categories</a>
  </li>
        
        
        
          
          <li class="menu-item menu-item-archives">
    <a href="/archives/" rel="section">
      <i class="menu-item-icon fa fa-fw fa-archive"></i> <br />Archives</a>
  </li>

      
      
    </ul>
  

  
    

  

  
</nav>



  



</div>
    </header>

    


    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          
          <div id="content" class="content">
            

  <div id="posts" class="posts-expand">
    
    
    
    <div class="post-block page">
      <header class="post-header">

<h1 class="post-title" itemprop="name headline">Python Traceback 详解</h1>

<div class="post-meta">
  
  


  
  
  <ul class="breadcrumb">
    
      
      
        
          <li><a href="/2017/">2017</a></li>
          
            
          
        
      
    
      
      
        
          <li><a href="/2017/02/">02</a></li>
          
            
          
        
      
    
      
      
        
          <li><a href="/2017/02/07/">07</a></li>
          
            
          
        
      
    
      
      
        
          <li>PYTHON_TRACEBACK</li>
        
      
    
      
      
        
          <li><a href="/2017/02/07//"></a></li>
          
            
          
        
      
    
  </ul>


</div>

</header>

      
      
      
      <div class="post-body">
        
        
          <p>刚接触Python的时候，简单的异常处理已经可以帮助我们解决大多数问题，但是随着逐渐地深入，我们会发现有很多情况下简单的异常处理已经无法解决问题了，如下代码，单纯的打印异常所能提供的信息会非常有限。</p>
<p>&lt;!--more--&gt;</p>
<p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line">def func1():</span><br><span class="line">    raise Exception(&quot;--func1 exception--&quot;)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def main():</span><br><span class="line">    try:</span><br><span class="line">        func1()</span><br><span class="line">    except Exception as e:</span><br><span class="line">        print e</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">if __name__ == &apos;__main__&apos;:</span><br><span class="line">    main()</span><br></pre></td></tr></table></figure></p>
<p>执行后输出如下：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">--func1 exception--</span><br></pre></td></tr></table></figure></p>
<p>通过示例，我们发现普通的打印异常只有很少量的信息（通常是异常的value值），这种情况下我们很难定位在哪块代码出的问题，以及如何出现这种异常。那么到底要如何打印更加详细的信息呢？下面我们就来一一介绍。</p>
<h3>sys.exc_info和traceback object</h3>
<p>Python程序的traceback信息均来源于一个叫做<strong>traceback object</strong>的对象，而这个traceback object通常是通过函数sys.exc_info()来获取的，先来看一个例子：</p>
<p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line">import sys</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def func1():</span><br><span class="line">    raise NameError(&quot;--func1 exception--&quot;)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def main():</span><br><span class="line">    try:</span><br><span class="line">        func1()</span><br><span class="line">    except Exception as e:</span><br><span class="line">        exc_type, exc_value, exc_traceback_obj = sys.exc_info()</span><br><span class="line">        print &quot;exc_type: %s&quot; % exc_type</span><br><span class="line">        print &quot;exc_value: %s&quot; % exc_value</span><br><span class="line">        print &quot;exc_traceback_obj: %s&quot; % exc_traceback_obj</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">if __name__ == &apos;__main__&apos;:</span><br><span class="line">    main()</span><br></pre></td></tr></table></figure></p>
<p>执行后输出如下：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br></pre></td><td class="code"><pre><span class="line">exc_type: &lt;type &apos;exceptions.NameError&apos;&gt;</span><br><span class="line">exc_value: --func1 exception--</span><br><span class="line">exc_traceback_obj: &lt;traceback object at 0x7faddf5d93b0&gt;</span><br></pre></td></tr></table></figure></p>
<p>通过以上示例我们可以看出，sys.exc_info()获取了当前处理的exception的相关信息，并返回一个元组，元组的第一个数据是异常的类型(示例是NameError类型)，第二个返回值是异常的value值，第三个就是我们要的traceback object.</p>
<p>有了traceback object我们就可以通过traceback module来打印和格式化traceback的相关信息，下面我们就来看下traceback module的相关函数。</p>
<h3>traceback module</h3>
<p>Python的traceback module提供一整套接口用于提取，格式化和打印Python程序的stack traces信息，下面我们通过例子来详细了解下这些接口：</p>
<h4>print_tb</h4>
<p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line">import sys</span><br><span class="line">import traceback</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def func1():</span><br><span class="line">    raise NameError(&quot;--func1 exception--&quot;)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def main():</span><br><span class="line">    try:</span><br><span class="line">        func1()</span><br><span class="line">    except Exception as e:</span><br><span class="line">        exc_type, exc_value, exc_traceback_obj = sys.exc_info()</span><br><span class="line">        traceback.print_tb(exc_traceback_obj)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">if __name__ == &apos;__main__&apos;:</span><br><span class="line">    main()</span><br></pre></td></tr></table></figure></p>
<p>输出：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">File &quot;&lt;ipython-input-23-52bdf2c9489c&gt;&quot;, line 11, in main</span><br><span class="line">    func1()</span><br><span class="line">File &quot;&lt;ipython-input-23-52bdf2c9489c&gt;&quot;, line 6, in func1</span><br><span class="line">    raise NameError(&quot;--func1 exception--&quot;)</span><br></pre></td></tr></table></figure></p>
<p>这里我们可以发现打印的异常信息更加详细了，下面我们了解下print_tb的详细信息：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">traceback.print_tb(tb[, limit[, file]])</span><br></pre></td></tr></table></figure></p>
<ul>
<li>tb: 这个就是traceback object, 是我们通过sys.exc_info获取到的</li>
<li>limit: 这个是限制stack trace层级的，如果不设或者为None，就会打印所有层级的stack trace</li>
<li>file: 这个是设置打印的输出流的，可以为文件，也可以是stdout之类的file-like object。如果不设或为None，则输出到sys.stderr。</li>
</ul>
<h4>print_exception</h4>
<p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line">import sys</span><br><span class="line">import traceback</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def func1():</span><br><span class="line">    raise NameError(&quot;--func1 exception--&quot;)</span><br><span class="line"></span><br><span class="line">def func2():</span><br><span class="line">    func1()</span><br><span class="line"></span><br><span class="line">def main():</span><br><span class="line">    try:</span><br><span class="line">        func2()</span><br><span class="line">    except Exception as e:</span><br><span class="line">        exc_type, exc_value, exc_traceback_obj = sys.exc_info()</span><br><span class="line">        traceback.print_exception(exc_type, exc_value, exc_traceback_obj, limit=2, file=sys.stdout)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">if __name__ == &apos;__main__&apos;:</span><br><span class="line">    main()</span><br></pre></td></tr></table></figure></p>
<p>输出：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br></pre></td><td class="code"><pre><span class="line">Traceback (most recent call last):</span><br><span class="line">  File &quot;&lt;ipython-input-24-a68061acf52f&gt;&quot;, line 13, in main</span><br><span class="line">    func2()</span><br><span class="line">  File &quot;&lt;ipython-input-24-a68061acf52f&gt;&quot;, line 9, in func2</span><br><span class="line">    func1()</span><br><span class="line">NameError: --func1 exception--</span><br></pre></td></tr></table></figure></p>
<p>看下定义：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">traceback.print_exception(etype, value, tb[, limit[, file]])</span><br></pre></td></tr></table></figure></p>
<ul>
<li>跟print_tb相比多了两个参数etype和value，分别是exception type和exception value，加上tb(traceback object)，正好是sys.exc_info()返回的三个值</li>
<li>另外，与print_tb相比，打印信息多了开头的&quot;Traceback (most...)&quot;信息以及最后一行的异常类型和value信息</li>
<li>还有一个不同是当异常为SyntaxError时，会有&quot;^&quot;来指示语法错误的位置</li>
</ul>
<h4>print_exc</h4>
<p>print_exc是简化版的print_exception, 由于exception type, value和traceback object都可以通过sys.exc_info()获取，因此print_exc()就自动执行exc_info()来帮助获取这三个参数了，也因此这个函数是我们的程序中最常用的，因为它足够简单
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line">import sys</span><br><span class="line">import traceback</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">def func1():</span><br><span class="line">    raise NameError(&quot;--func1 exception--&quot;)</span><br><span class="line"></span><br><span class="line">def func2():</span><br><span class="line">    func1()</span><br><span class="line"></span><br><span class="line">def main():</span><br><span class="line">    try:</span><br><span class="line">        func2()</span><br><span class="line">    except Exception as e:</span><br><span class="line">        traceback.print_exc(limit=1, file=sys.stdout)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">if __name__ == &apos;__main__&apos;:</span><br><span class="line">    main()</span><br></pre></td></tr></table></figure></p>
<p>输出（由于limit=1，因此只有一个层级被打印出来）：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br></pre></td><td class="code"><pre><span class="line">Traceback (most recent call last):</span><br><span class="line">  File &quot;&lt;ipython-input-25-a1f5c73b97c4&gt;&quot;, line 13, in main</span><br><span class="line">    func2()</span><br><span class="line">NameError: --func1 exception--</span><br></pre></td></tr></table></figure></p>
<p>定义如下：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br></pre></td><td class="code"><pre><span class="line">traceback.print_exc([limit[, file]])</span><br></pre></td></tr></table></figure></p>
<ul>
<li>只有两个参数，够简单</li>
</ul>
<h4>format_exc</h4>
<p><figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line">import logging</span><br><span class="line">import sys</span><br><span class="line">import traceback</span><br><span class="line">logger = logging.getLogger(&quot;traceback_test&quot;)</span><br><span class="line"></span><br><span class="line">def func1():</span><br><span class="line">    raise NameError(&quot;--func1 exception--&quot;)</span><br><span class="line"></span><br><span class="line">def func2():</span><br><span class="line">    func1()</span><br><span class="line"></span><br><span class="line">def main():</span><br><span class="line">    try:</span><br><span class="line">        func2()</span><br><span class="line">    except Exception as e:</span><br><span class="line">        logger.error(traceback.format_exc(limit=1, file=sys.stdout))</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">if __name__ == &apos;__main__&apos;:</span><br><span class="line">    main()</span><br></pre></td></tr></table></figure></p>
<p>从这个例子可以看出有时候我们想得到的是一个字符串，比如我们想通过logger将异常记录在log里，这个时候就需要format_exc了，这个也是最常用的一个函数，它跟print_exc用法相同，只是不直接打印而是返回了字符串。</p>
<p>traceback module中还有一些其它的函数，但因为并不常用，就不在展开来讲，感兴趣的同学可以看下参考链接中的文档。</p>
<h3>获取线程中的异常信息</h3>
<p>通常情况下我们无法将多线程中的异常带回主线程，所以也就无法打印线程中的异常，而通过上边学到这些知识，我们可以对线程做如下修改，从而实现捕获线程异常的目的。
以下示例来自weidong的博客文章，稍有修改（见参考链接）
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br><span class="line">21</span><br><span class="line">22</span><br><span class="line">23</span><br><span class="line">24</span><br><span class="line">25</span><br><span class="line">26</span><br><span class="line">27</span><br><span class="line">28</span><br><span class="line">29</span><br><span class="line">30</span><br><span class="line">31</span><br><span class="line">32</span><br><span class="line">33</span><br><span class="line">34</span><br><span class="line">35</span><br><span class="line">36</span><br><span class="line">37</span><br><span class="line">38</span><br><span class="line">39</span><br><span class="line">40</span><br><span class="line">41</span><br><span class="line">42</span><br><span class="line">43</span><br><span class="line">44</span><br><span class="line">45</span><br><span class="line">46</span><br><span class="line">47</span><br></pre></td><td class="code"><pre><span class="line">import threading</span><br><span class="line">import traceback</span><br><span class="line"></span><br><span class="line">def my_func():</span><br><span class="line">    raise BaseException(&quot;thread exception&quot;)</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">class ExceptionThread(threading.Thread):</span><br><span class="line"></span><br><span class="line">    def __init__(self, group=None, target=None, name=None, args=(), kwargs=None, verbose=None):</span><br><span class="line">        &quot;&quot;&quot;</span><br><span class="line">        Redirect exceptions of thread to an exception handler.</span><br><span class="line">        &quot;&quot;&quot;</span><br><span class="line">        threading.Thread.__init__(self, group, target, name, args, kwargs, verbose)</span><br><span class="line">        if kwargs is None:</span><br><span class="line">            kwargs = &#123;&#125;</span><br><span class="line">        self._target = target</span><br><span class="line">        self._args = args</span><br><span class="line">        self._kwargs = kwargs</span><br><span class="line">        self._exc = None</span><br><span class="line"></span><br><span class="line">    def run(self):</span><br><span class="line">        try:</span><br><span class="line">            if self._target:</span><br><span class="line">                self._target()</span><br><span class="line">        except BaseException as e:</span><br><span class="line">            import sys</span><br><span class="line">            self._exc = sys.exc_info()</span><br><span class="line">        finally:</span><br><span class="line">            #Avoid a refcycle if the thread is running a function with</span><br><span class="line">            #an argument that has a member that points to the thread.</span><br><span class="line">            del self._target, self._args, self._kwargs</span><br><span class="line"></span><br><span class="line">    def join(self):</span><br><span class="line">        threading.Thread.join(self)</span><br><span class="line">        if self._exc:</span><br><span class="line">            msg = &quot;Thread &apos;%s&apos; threw an exception: %s&quot; % (self.getName(), self._exc[1])</span><br><span class="line">            new_exc = Exception(msg)</span><br><span class="line">            raise new_exc.__class__, new_exc, self._exc[2]</span><br><span class="line"></span><br><span class="line"></span><br><span class="line">t = ExceptionThread(target=my_func, name=&apos;my_thread&apos;)</span><br><span class="line">t.start()</span><br><span class="line">try:</span><br><span class="line">    t.join()</span><br><span class="line">except:</span><br><span class="line">    traceback.print_exc()</span><br></pre></td></tr></table></figure></p>
<p>输出如下：
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br></pre></td><td class="code"><pre><span class="line">Traceback (most recent call last):</span><br><span class="line">  File &quot;/data/code/testcode/thread_exc.py&quot;, line 43, in &lt;module&gt;</span><br><span class="line">    t.join()</span><br><span class="line">  File &quot;/data/code/testcode/thread_exc.py&quot;, line 23, in run</span><br><span class="line">    self._target()</span><br><span class="line">  File &quot;/data/code/testcode/thread_exc.py&quot;, line 5, in my_func</span><br><span class="line">    raise BaseException(&quot;thread exception&quot;)</span><br><span class="line">Exception: Thread &apos;my_thread&apos; threw an exception: thread exception</span><br></pre></td></tr></table></figure></p>
<p>这样我们就得到了线程中的异常信息。</p>
<h3>参考链接</h3>
<p><a href="https://docs.python.org/2/library/traceback.html" target="_blank" rel="noopener">traceback官方文档</a></p>
<p><a href="http://swdtalent.github.io/weidong.github.com/2015-10-24/python-catch-thread-exception/" target="_blank" rel="noopener">weidong's blog</a></p>

        
      </div>
      
      
      
    </div>
    


  
  
  <ul class="breadcrumb">
    
      
      
        
          <li><a href="/2017/">2017</a></li>
          
            
          
        
      
    
      
      
        
          <li><a href="/2017/02/">02</a></li>
          
            
          
        
      
    
      
      
        
          <li><a href="/2017/02/07/">07</a></li>
          
            
          
        
      
    
      
      
        
          <li>PYTHON_TRACEBACK</li>
        
      
    
      
      
        
          <li><a href="/2017/02/07//"></a></li>
          
            
          
        
      
    
  </ul>


    
    
    
  </div>


          </div>
          

  
    <div class="comments" id="comments">
    </div>
  



        </div>
        
          
  
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>

  <aside id="sidebar" class="sidebar">
    
    <div class="sidebar-inner">

      

      
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap">
            Table of Contents
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview-wrap">
            Overview
          </li>
        </ul>
      

      <section class="site-overview-wrap sidebar-panel">
        <div class="site-overview">
          <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
            
              <p class="site-author-name" itemprop="name">geekpy</p>
              <p class="site-description motion-element" itemprop="description"></p>
          </div>

          
            <nav class="site-state motion-element">
              
                <div class="site-state-item site-state-posts">
                
                  <a href="/archives/">
                
                    <span class="site-state-item-count">28</span>
                    <span class="site-state-item-name">posts</span>
                  </a>
                </div>
              

              

              
                
                
                <div class="site-state-item site-state-tags">
                  <a href="/tags/index.html">
                    
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                      
                    
                    <span class="site-state-item-count">7</span>
                    <span class="site-state-item-name">tags</span>
                  </a>
                </div>
              
            </nav>
          

          
            <div class="feed-link motion-element">
              <a href="/atom.xml" rel="alternate">
                <i class="fa fa-rss"></i>
                RSS
              </a>
            </div>
          

          
            <div class="links-of-author motion-element">
              
                <span class="links-of-author-item">
                  <a href="https://github.com/geekpy" target="_blank" title="GitHub"><i class="fa fa-fw fa-github"></i>GitHub</a>
                  
                </span>
              
                <span class="links-of-author-item">
                  <a href="mailto:rebor.liu@gmail.com" target="_blank" title="E-Mail"><i class="fa fa-fw fa-envelope"></i>E-Mail</a>
                  
                </span>
              
            </div>
          

          
          

          
          

          
            
          
          

        </div>
      </section>

      
      <!--noindex-->
        <section class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">

            
              
            

            
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-3"><a class="nav-link" href="#undefined"><span class="nav-number">1.</span> <span class="nav-text">sys.exc_info和traceback object</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#undefined"><span class="nav-number">2.</span> <span class="nav-text">traceback module</span></a><ol class="nav-child"><li class="nav-item nav-level-4"><a class="nav-link" href="#undefined"><span class="nav-number">2.1.</span> <span class="nav-text">print_tb</span></a></li><li class="nav-item nav-level-4"><a class="nav-link" href="#undefined"><span class="nav-number">2.2.</span> <span class="nav-text">print_exception</span></a></li><li class="nav-item nav-level-4"><a class="nav-link" href="#undefined"><span class="nav-number">2.3.</span> <span class="nav-text">print_exc</span></a></li><li class="nav-item nav-level-4"><a class="nav-link" href="#undefined"><span class="nav-number">2.4.</span> <span class="nav-text">format_exc</span></a></li></ol></li><li class="nav-item nav-level-3"><a class="nav-link" href="#undefined"><span class="nav-number">3.</span> <span class="nav-text">获取线程中的异常信息</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#undefined"><span class="nav-number">4.</span> <span class="nav-text">参考链接</span></a></li></ol></div>
            

          </div>
        </section>
      <!--/noindex-->
      

      

    </div>
  </aside>


        
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="footer-inner">
        <div class="copyright">&copy; <span itemprop="copyrightYear">2018</span>
  <span class="with-love" id="animate">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">geekpy</span>

  

  
</div>




  <div class="powered-by">Powered by <a class="theme-link" target="_blank" href="https://hexo.io">Hexo</a> v3.7.1</div>



  <span class="post-meta-divider">|</span>



  <div class="theme-info">Theme – <a class="theme-link" target="_blank" href="https://theme-next.org">NexT.Muse</a> v6.4.2</div>




        








        
      </div>
    </footer>

    
      <div class="back-to-top">
        <i class="fa fa-arrow-up"></i>
        
      </div>
    

    
	
    

    
  </div>

  

<script type="text/javascript">
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>


























  
  
    <script type="text/javascript" src="/lib/jquery/index.js?v=2.1.3"></script>
  

  
  
    <script type="text/javascript" src="/lib/velocity/velocity.min.js?v=1.2.1"></script>
  

  
  
    <script type="text/javascript" src="/lib/velocity/velocity.ui.min.js?v=1.2.1"></script>
  


  


  <script type="text/javascript" src="/js/src/utils.js?v=6.4.2"></script>

  <script type="text/javascript" src="/js/src/motion.js?v=6.4.2"></script>



  
  

  
  <script type="text/javascript" src="/js/src/scrollspy.js?v=6.4.2"></script>
<script type="text/javascript" src="/js/src/post-details.js?v=6.4.2"></script>



  


  <script type="text/javascript" src="/js/src/bootstrap.js?v=6.4.2"></script>



  



  








  <script src="//cdn1.lncld.net/static/js/3.0.4/av-min.js"></script>
  
  
  <script src="//unpkg.com/valine/dist/Valine.min.js"></script>
  
  <script type="text/javascript">
    var GUEST = ['nick','mail','link'];
    var guest = 'nick,mail,link';
    guest = guest.split(',').filter(function (item) {
      return GUEST.indexOf(item)>-1;
    });
    new Valine({
        el: '#comments' ,
        verify: false,
        notify: false,
        appId: 'OCjgmQiFa9gpVkDabM6KTb8g-gzGzoHsz',
        appKey: 'Ie7XE2V6spB6Q6C1W2GU9drV',
        placeholder: 'Just go go',
        avatar:'mm',
        meta:guest,
        pageSize:'10' || 10,
        visitor: false
    });
  </script>



  





  

  

  

  

  
  

  

  

  

  

  

</body>
</html>
